version: '3'
services:
  # To run several containers in parallel use scale argument:
  # docker-compose up --build --scale app=5
  app:
    build: .
    restart: always # Re-run after system reboot or docker daemon restart.
    environment:
      NO_COLOR: 'true' # Disables colored output for better logs in clouds.
      # Print summary table with results.
      LOG_SUMMARY_TABLE: 'false'
      # Log response status codes to console during load testing.
      LOG_RESPONSE_SUCCESS: 'false'
      LOG_RESPONSE_TIMEOUT: 'false'
      LOG_RESPONSE_ERROR: 'false'
      # UAShield settings.
      UASHIELD_USE_PROXY: 'true'
      UASHIELD_PROXIES: 'https://raw.githubusercontent.com/opengs/uashieldtargets/v2/proxy.json'
      UASHIELD_URLS: 'https://raw.githubusercontent.com/opengs/uashieldtargets/v2/sites.json'
      ## Override UAShield URLs. Needs to be valid JSON array with URLs.
      #UASHIELD_TARGETS: '["https://kremlin.ru", "https://www.sberbank.ru"]'
